### ISSUE TITLE
Service based method not working in symfony 4.4

### ISSUE THREAD

**Issue by oussama-aitmi** [rdohms/dms-filter-bundle#153]
I am using symfony4.4 with the bundle dms-filter-bundle 4.0
when I call my filter I get any result and any error, 
here is my filter from my entity :
<pre>
    /**
     * @ORM\Column(type="guid")
     * @SfFilter\Service(service="App\Rules\DocumentRules", method="uid")
     */
    protected $uid;
</pre>

**Comment by rdohms** [comment]
Support for Symfony 4 has been dropped, please re-open if still an issue in Sf 5.
