### ISSUE TITLE
No need to register annotation namespace?

### ISSUE THREAD

**Issue by gfreeau** [rdohms/dms-filter-bundle#21]
I believe this is not needed in the bundle extension:

``` php
AnnotationRegistry::registerAutoloadNamespace('DMS\Bundle\FilterBundle\Rule', __DIR__ . '/../../../');
```

as long as you register the annotations loader in app/autoload.php

``` php
AnnotationRegistry::registerLoader(array($loader, 'loadClass'));
```

This allows for other symfony annotations as well:

http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html

**Comment by rdohms** [comment]
No longer relevant since we deprecated annotations in v6. Closed by #302 
Thanks for the report.
