### ISSUE TITLE
Symfony 3.0 comptibility

### ISSUE THREAD

**Issue by rdohms** [rdohms/dms-filter-bundle#27]
In order to make the bundle compatible with 3.0 we need to break BC for versions below 2.8 of Symfony.

So v2 will remain symfony 2.3+ compatible and the new v3 release will be 2.8 | 3.* compatible.

**Comment by rdohms** [comment]
@msvrtan that would be awesome

**Comment by msvrtan** [comment]
@rdohms just sent the PR #28

**Comment by ttibensky** [comment]
```
Tagged form type extension must have the extended type configured using the extended_type/extended-type attribute
```

Do you have a version which is fully compatible with symfony3 or should I fix it and create a PR?

**Comment by ttibensky** [comment]
actually, just create a new tag so we don't need to have your library open using `dev-master`

**Comment by rdohms** [comment]
v3.0 has been released.
