### ISSUE TITLE
Annotate Service with Attributes

### ISSUE THREAD

**Issue by StefanGlaesser** [rdohms/dms-filter-bundle#286]
Hello,

I have the following Annotations and Attributes set on an property:

      /**
       * @SfFilter\Service(service="app.utitliy_service", method="removeWhiteSpaces")
       */
       #[Filter\StripTags]
       #[Filter\Trim]
       #[ORM\Column(type: 'string', nullable: true)]
       private ?string $author = null;

I can't neither use this (syntax seems to be correct, but it doesn't work):

       #[SfFilter\Service(options: ["service" => UtilityService::class, "method" => "removeWhiteSpaces"])]

       #[SfFilter\Service(options: ["service" => "app.utitliy_service", "method" => "removeWhiteSpaces"])]

nor use that (for which phpstorm also reclaims syntax error):

       #SfFilter\Service(service: UtilityService::class, method: "removeWhiteSpaces")]

So please what's the correct syntax for using own Filter-methods with attributes? It looks, that Attribute-Syntax doesn't work?!?

Best regards,
Stefan

**Comment by igordeveloper** [comment]
#302

**Comment by rdohms** [comment]
Closed by #302
