### ISSUE TITLE
Just not working?

### ISSUE THREAD

**Issue by ghost** [rdohms/dms-filter-bundle#32]
Hi

I have installed via composer and registered the bundle in AppKernal and have the following

`
namespace AppBundle\Entity;
use DMS\Filter\Rules as Filter;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 250,
     *      minMessage = "Your description must be at least {{ limit }} characters long",
     * )
     * @Filter\StripTags()
     * @Filter\Trim()
     */
    private $description;
`

Yet I when I submit the form with something like <p>xyz</p> or <script>abc</script> the tags are not stripped.  

Have I missed something?

**Comment by rdohms** [comment]
@imogenhallett can you give more info about which Symfony you are running? Also can you call the filter service directly with this entity and see if the effect is as expected?
